### ISSUE TITLE
compilation errors for dependency EmbeddedUtilities version 0.3.1

### ISSUE THREAD

**Issue by Annika10** [es-ude/PeripheralInterface#7]
The PeripheralInterface repo uses the EmbeddedUtilities repo version 0.3. Because of renaming folders in EmbeddedUtilities version 0.3.1 you run in version conflicts and compilation errors when you use the newer version and the PeripheralInterface repo in your own project. 

For example PeripheralInterface.h uses #include "Util/Callback.h". In EmbeddedUtilities version 0.3.1 the path has to be "#include EmbeddedUtilities/Callback.h".

**Comment by boehnsins** [comment]
fixed in d088a4967aca88f78e295f4facb2d576f2a22a7d and released in Peripheral Interface v0.7.1
